[package]
name = "widget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
regex = "1.7.1"
uptime_lib = "0.2.2"
chrono = "0.4.24"
